version: '3.5'
services:
  api1: # API - Instância 01
    image: webapp
    build: .
    hostname: api1
    command: python wsgi.py
    depends_on:
      - db
    ports:
      - "8080:8080"
    # expose:
      # - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    volumes:
      - ./app:/app

  api2: # API - Instância 01
    image: webapp
    build: .
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    volumes:
      - ./app:/app

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      # - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres:latest
    environment:
      POSTGRES_DB: "POSTGRES"
      POSTGRES_USER: "POSTGRES"
      POSTGRES_PASSWORD: "POSTGRES"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    volumes:
      - ./pg:/var/lib/postgresql/data
